import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/shared/main_header";
import localFont from 'next/font/local'
import { inter } from "@/lib/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`bg-[#EDF3F2] ${inter.className}`}>
        <MainHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
